version: "3.8"
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"  # Set your own strong password here
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"  # Expose the SQL Server port
    volumes:
      - ./data:/var/opt/mssql/data
  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: projects/APIGateway/APIGateway/Dockerfile
    ports:
      - "8085:8085"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  seq:
    image: datalust/seq
    ports:
      - "5341:5341"
      - "4342:80"
    volumes:
      - rps_seq_data1:/data
    environment:
      - ACCEPT_EULA=Y
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 3
  inventoryservice:
    image: inventoryservice
    build:
      context: .
      dockerfile: projects/inventory-service/InventoryService/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - apigateway
      - rabbitmq
  orderservice:
    image: orderservice
    build:
      context: .
      dockerfile: projects/order-service/OrderService/Dockerfile
    ports:
      - "8082:80"
    depends_on:
      - apigateway
      - rabbitmq
  authservice:
    image: authservice
    build:
      context: .
      dockerfile: projects/auth-service/AuthService/Dockerfile
    ports:
      - "8083:80"
    depends_on:
      - apigateway

    test:
      build:
        context: .
        dockerfile: tests/authservice.tests/Dockerfile
      command: dotnet test tests/authservice.tests/authservice.tests.csproj
volumes:
  rps_seq_data1:

