apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: authservice
        imagePullPolicy: Never
        ports:
        - containerPort: 8083
        env:
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-server-secret
              key: SA_PASSWORD
        envFrom:
        - configMapRef: 
            name: auth-sql-server-config
        - configMapRef: 
            name: base-config
