controller:
  customJenkinsLabels:
    - docker

  image: 
    repository: jenkins/jenkins
    tag: lts

  initContainers:
    - name: install-docker
      image: docker:20.10.7
      command: ['sh', '-c', 'apk add --no-cache docker && cp /usr/local/bin/docker /usr/bin/docker']

  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock

  containers:
    - name: jenkins
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock

  securityContext:
    runAsUser: 0
    fsGroup: 0

  service:
    type: LoadBalancer
    port: 8080
