apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: inventoryservice
        imagePullPolicy: Never
        ports:
        - containerPort: 8083
        env:
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-server-secret
              key: SA_PASSWORD
        envFrom:
        - configMapRef: 
            name: base-config
        - configMapRef: 
            name: inventory-sql-server-config

