apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: orderservice
        imagePullPolicy: Never
        ports:
        - containerPort: 8083
        env:
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-server-secret
              key: SA_PASSWORD
        envFrom:
        - configMapRef: 
            name: base-config
        - configMapRef: 
            name: order-sql-server-config

